spring:
  application:
    name: app-consumer-message-rabbitmq

  jackson:
    serialization:
      write_dates_as_timestamps: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

com:
  template:
    rabbitmq:
      exchange: test.exchange
      queue: com.create.product.Queue
